version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000" # Maps port 3000 on the host to port 3000 in the container
    volumes:
      - /home/subrata/www/recurring-date-picker:/app # Mounts the project directory for live code changes (development mode)
      - /app/node_modules # Prevents overwriting the container's node_modules
